In [121]:
import pandas as pd
cp = pd.read_excel('Dataset.xlsx')
cp.head()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,2001-12-01 00:00:00,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,06/14/2023 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,"45235 days, 0:21:29",2022-03-11 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,1999-01-11 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39

- check the datatypes of each column

In [51]:
#Display the datatypes of each column in the dataframe
cp.dtypes

Learner SignUp DateTime            object
Opportunity Id                     object
Opportunity Name                   object
Opportunity Category               object
Opportunity End Date               object
First Name                         object
Date of Birth                      object
Gender                             object
Country                            object
Institution Name                   object
Current/Intended Major             object
Entry created at           datetime64[ns]
Status Description                 object
Status Code                         int64
Apply Date                         object
Opportunity Start Date             object
dtype: object

**Data Cleaning**

In [53]:
# Check data quality issues
print("Data Quality Issues:")
print(f"Missing values:\n{cp.isnull().sum()}")
print(f"\nDuplicate rows: {cp.duplicated().sum()}")

# Check for inconsistent categorical values
print(f"\nUnique values in categorical columns:")
categorical_cols = ['Gender', 'Country','Opportunity Category','Institution Name', 'Current/Intended Major', 'Status Description', 'Opportunity Name','Status Code']
for col in categorical_cols:
    if col in cp.columns:
        print(f"{col}: {cp[col].unique()}")

Data Quality Issues:
Missing values:
Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
dtype: int64

Duplicate rows: 0

Unique values in categorical columns:
Gender: ['Female' 'Male' "Don't want to specify" 'Other']
Country: ['Pakistan' 'India' 'United States' 'United Arab Emirates' 'Nigeria'
 'Egypt' 'Nepal' 'Kenya' 'Ghana' 'Zambia' 'Morocco' 'Ethiopia' 'Zimbabwe'
 'Uganda' 'Indonesia' 'Cameroon' 'Yemen' 'China' 'Bangladesh' 'Congo'
 'Liberia' 'United Kingdom' 'Vietnam' 'Japan' 'Rwanda' 'Gambia'
 'Philippines' 'Australia' 'Somalia' 'Sierra Leone' 'Lebanon' 'Botswana'
 'Iraq' 'Uzbekistan' 'Turkey' 'Honduras'
 'Tanzania, United Republic of Tanzania' 'British Indian Ocean Territory'
 'France' 'Belarus' 'Algeria' 'Korea, Republic of South Korea' 'Mauritius'
 'Tunisia' 'Kazakhstan' 'Peru' 'Brazil' 'Ukraine' 'South Africa' 'Germany'
 'Namibia' 'Iran, Islamic Republic of Persian Gulf' 'American Samoa'
 'Falkland Islands (Malvinas)' 'Saudi Arabia' 'Sri Lanka' 'Azerbaijan'
 'Dominican Republic' 'Lesotho' 'Malaysia' 'Virgin Islands, U.S.' 'Qatar'
 'Canada' 'Singapore' 'Iran  Islamic Republic of Persian Gulf' 'Ireland'
 'Libyan Arab Jamahiriya' "Cote d'Ivoire" 'Afghanistan' 'Bhutan' 'Spain']
Opportunity Category: ['Course' 'Competition' 'Internship' 'Event' 'Engagement']
Institution Name: ['Nwihs' 'SAINT LOUIS' 'Illinois Institute of Technology' ...
 'Jawaharlal Nehru technological University of Hyderabad'
 'Kwara state University' 'Tai Solarin university of Education']
Current/Intended Major: ['Radiology' 'Information Systems' 'Computer Science'
 'Mechanical Engineering' 'Computer Science and Engineering'
 'Artificial Intelligence' 'Robotics and Automation Engineering'
 'Data Visualization' 'Business Administration' 'Public Health'
 'Architecture' 'Computer Science and Information Systems' 'Biology'
 'Economics' 'Oth' 'Mathematics' 'Bioinformatics' 'I Am Major'
 'Biomedical Engineering' 'Electrical and Electronic Engineering'
 'Business and Management Studies' 'Electrical and Computer Engineering'
 'Accounting and Finance' 'Secretarial' 'Data Science' 'Statistics'
 'Electronics and Communication' 'Computer Information Systems'
 'Management Information Systems' 'Other' 'Project Management' 'Medicine'
 'Information' 'Information Technology' 'Actuarial Mathematics'
 'Software Engineering' 'Biological Sciences'
 'Urban and Housing Development' 'Human Resources' 'Cyber Security'
 'Data Analytics' 'Computer Engineering' 'Environmental Sciences'
 'Philosophy' 'Law and Legal Studies' 'Student' 'Industrial Engineering'
 'Theology or Divinity and Religious Studies' 'Business Analytics'
 'Artificial Intelligence and Machine learning' 'Agriculture and Forestry'
 'International Business Management' 'Politics' 'Marketing'
 'Pure and Applied Physics' 'Biochemistry'
 'Information Technology and Management' 'Civil Engineering' 'English'
 'Electrical Engineering' 'Eee' 'Social Work' 'Cybersecurity'
 'Computer Science with Internet of Things' 'Pharmacy and Pharmacology'
 'Nutrition Science' 'Pol' 'Metallurgy and Materials Engineering'
 'Finance' 'Geography' 'Information technology and management'
 'English Language and Literature' 'Dentistry' 'Communication' 'Chemistry'
 'Food Science' 'Psychology' 'MS in Supply Chain Management'
 'English Linguistics' 'Hospitality and Leisure Management'
 'Financial Technology' 'Mass Communication' 'Information technology'
 'Health Data Science' 'Electronics and Communication Engineering'
 'Quantity Surveying' 'Masters in Computer Science' 'Commerce'
 'Environmental and Safety Engineering' 'Network and Information Security'
 'Cloud Computing' 'MBA' 'Fresher' 'Computer Applications'
 'Mechanical and Aerospace Engineering' 'Mechatronics Engineering'
 'Supply Chain Management' 'Nursing' 'Political Science'
 'Animal Production and Health' 'Faizan' 'International Relations'
 'Artificial Intelligence and Robotics' 'Not Know Ab' 'Health Education'
 'Public Administration' 'Btech' 'Radiation Therapy' 'Digital Marketing'
 'Engineering' 'Associate of Science' 'Education and Training'
 'Aerospace Engineering' 'Bachelor of Engineering' 'Sociology' 'Degree'
 'Marketing Analytics' 'Medical Sciences' 'Finance and Banking'
 'Art and Design' 'BSIT' 'Physics and Astronomy' 'Chemical Engineering'
 'Business Chinese' 'Music' 'Earth and Marine Sciences' 'ANALYTICS' 'Job'
 'Leadership' 'Agricultural Extension and Education'
 'Education Management' 'Applied Financial Economics' 'DOCTOR of PHARMACY'
 'Bsc Agri' 'Research' 'Information Science' 'Management' 'Non' 'Sdada'
 'Telecommunication Engineering' 'ESports and Game Development'
 'Epidemiology' 'Petroleum Engineering' 'Procurement' 'Biotechnology'
 'Airline Pilot' 'Food Safety and Technology' 'Systems Engineering' 'Ghj'
 'Na' 'Pre Engg' 'Civil and Structural Engineering' 'Entrepreneurship'
 'Program in Exploratory Studies' 'Architectural Engineering' 'General'
 'Geology' 'Neuroscience' 'Data Analysis' 'Gamer' 'Bsc Nursing'
 'Information Engineering' 'BBA' 'Medical Laboratory Science' 'MCA'
 'Human Resource' 'After Bachelor' 'Aeronautics' 'Engineers Physics'
 'Soil Science and Technology' 'Business' 'No'
 'Construction Engineering and Management'
 'Communication and Media Studies' 'Bs Forestry and Wildlife Management'
 'Medical Laboratory' 'Analytics' 'Aa'
 'Data Science and Artificial Intelligence'
 'Msc cyber forensics and security' 'Statistics and Operational Research'
 'Master in VLSI and Microelectronics' 'MMG' 'Accountancy'
 'Economics and Econometrics' 'Computer and Infromation Sciences'
 'Bsc in Computer Science' 'Community Health Officer' 'Social S'
 'Post Graduate Diploma in Public Health' 'Goodcreativity' 'Bachelor'
 'Monitoring and Evaluation' 'Electrical Engineer' 'Linguistics'
 'Voice Performance' 'Bachelor of Laws'
 'Library and Information Management' 'Ba Psych' 'Shaista' 'Ha' 'Forensic'
 'Forensic Science' 'SUPPLY CHAIN MANAGEMENT' 'Bcom' 'Masters'
 'Occupational Therapy' 'Law'
 'MSc in Computational Decision Science and Operations Research'
 'Rehabilitation and Mental Health Counseling'
 'Information technology Management' 'Archaeology' 'Logistics'
 'ENGINEERING Management' 'MASTERS in INFORMATION SYSTEMS'
 'Bnsc Nursing Science' 'Computer Science Engineering'
 'Aviation Management' 'Land Economy' 'ACCOUNTING' nan
 'Diploma in Visual Effects' 'Digital Media' 'Journalism'
 'Masters in Information Systems' 'Unemployed'
 'MS in Information Science Machine Learning' 'Applied Geophysics'
 'BCOM International Business' 'Functional Engineering'
 'Development Studies' 'AVIATION ADMINISTRATION' 'General Arts'
 'Computing' 'Diploma' 'Anatomy and Physiology'
 'Business Information Systems' 'Artificial Intelligence and Data Science'
 'Diploma in Automation and Robotics' 'BCA' 'Could Computing'
 'Advertising' 'Electronics and Computer Science Engineering' 'Physics'
 'Ot' 'MS Biostatistics and Health Analytics'
 'Information and Communication Engineering'
 'Computer Science and Business Systems' 'Dropped Out'
 'Electronics and Computers Engineering' 'Othe'
 'Social Policy and Administration' 'Computer and Information Sciences'
 'B TECH' 'Informatics' 'Medical Marketing or Medical Administration' 'TE'
 'Archeology and Cinematography' 'Carpentry and Joinery'
 'Guidance and Counseling' 'Computer' 'Manufacturing Engineering'
 'Manager' 'Computer and Information Sciencess' 'Bsc Physician Assistant'
 'Data Science and Business Analytics' 'Zoology' 'MBBS'
 'Computer applications' 'Home Economics' 'Paediatric Surgery'
 'Health Care Management' 'Food Process Engineering' 'Bioengineering'
 'Biomedical Science' 'Bsc' 'Aviation Maintenance' 'Microbiology'
 'Political Science and Spanish' 'Bba Hr' 'Radiography'
 'Clinical Research' 'INFORMATION SYSTEMS' 'Healthcare Management'
 'Medical Informatics' 'Geoinformatics and Geospatial Analytics'
 'Bachelor of Medicine Bachelor of Surgery' 'Applied Analytics'
 'Master of Public Health' 'To Study' 'Information systems'
 'Veterinary Science' 'Certificate' 'Medical Science' 'Midwifery'
 'Cyber Forensics and Security' 'Human Development and Family Science'
 'Dietetics' 'Speech and Language Therapy' 'Health Management'
 'General Science' 'Environmental Sustainability' 'Poetry'
 'Electronics and Computer Science' 'History'
 'MSc in Information technology' 'Tech and Business Management'
 'Communication and Software Engineer' 'Respiratory Therapy'
 'Health Information Management' 'Yoganand Sir' 'Data Analyst'
 'Procurement and Supply Chain Management' 'Arts' 'B Tech'
 'Computer science engineering' 'MS in Cybersecurity' 'Performing Arts'
 'Ms in Analytics' 'High School Certificate' 'BAF' 'Estate Management'
 'Lower Credit' 'Social Development and Policy' 'Automotive Engineering'
 'Textile' 'Education and Geography' 'Aeronautical Engineering'
 'General Management' 'Electronics and Computer Engineering'
 'Certification' 'Development Economics' 'Film Making'
 'Msc in Disaster Management and Climate Sustainability Studies'
 'International Development' 'Data Sceince' 'Animal Production'
 'COMPUTER SCIENCE and DESIGN' 'Business Informatics'
 'Mineral and Mining Engineering' 'Pursuing MCA' 'People Analytics'
 'Autonomous Systems and Robotics' 'Business Education' 'Data science'
 'Remote Sensing' 'Textile Engineering' 'Machine Learning' 'Analysis'
 'Physiotherapy' 'Statistics and Computeri Science' 'Honours'
 'International Business' 'Management Science and Analytics'
 'Actuarial Science' 'ISE' 'IT'
 'Electronics and Telecommunication Engineering' 'MECHANICAL'
 'Islamic Studies' 'Communication and Language Arts Education'
 'Early Childhood Education' 'Otheraassss' 'Multimedia Communication'
 'High School' 'Physical Therapy' 'Human Nutrition and Dietetics'
 'Health Sciences' 'Information Studies' 'General Practitioner'
 'Cyber Security and Digital Forensics' 'Entrepreneurship Studies'
 'American Sign Language Interpretation' 'B Sc' 'Nurse' 'Communications'
 'Brand Strategy' 'Fisheries' 'Www' 'High School Student'
 'Computer Science and Design' 'BSC Cs'
 'Msters in Healthcare Administration' 'Advertising and Packaging'
 'Computer Networking and IT Security' 'Already Graduation Completed'
 'Health Informatics' 'Health Systems Management and Development'
 'Geographic Information Science'
 'Agricultural Economics and Farm Management' 'Professional Courses'
 'ECONOMICS and FINANCE' 'Animal Science' 'GENERAL MANAGEMENT'
 'Electronics and Instrumentation' 'Bachelor of Computer' 'Accounting'
 'Working As Software Devloper' 'Pv'
 'Leadership and Organizational development' 'Home Tutor' 'Cycw'
 'Bachelor Degree in Nursing' 'Education Administration' 'Nil' 'Zack'
 'Pos Service']
Status Description: ['Started' 'Team Allocated' 'Waitlisted' 'Withdraw' 'Rewards Award'
 'Dropped Out' 'Rejected' 'Applied']
Opportunity Name: ['Career Essentials: Getting Started with Your Professional Journey'
 'Slide Geeks: A Presentation Design Competition' 'Digital Marketing'
 'Health Care Management' 'Innovation & Entrepreneurship'
 'Project Management' 'Data Visualization' 'CPR/AED Certification'
 'Mental and Physical Health Session'
 'Jump Start: Developing your Emotional Intelligence'
 'Join a Student Organisation' 'Upload Your First Year Transcript'
 'Startup Mastery Workshop' 'AI Ethics Challenge'
 'Data Visualization Associate' 'Digital Strategy Virtual Internship'
 'Project Management Associate' 'Business Consulting'
 'UrbanRenew Challenge' 'UX Redesign Challenge'
 'Xperience Design Hackathon' 'Freelance Mastery workshop']
Status Code: [1080 1070 1040 1110 1120 1050 1030 1010]

In [ ]:
#inputting nan is some missing valus (handling missing data)
cp['Opportunity Start Date']=cp['Opportunity Start Date'].fillna('unknown')
#Drop rows with null values from the dataframe (handling missing data)
cp.dropna()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,2001-12-01 00:00:00,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,06/14/2023 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,"45235 days, 0:21:29",2022-03-11 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,1999-01-11 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,10/14/2006,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,05/18/1999,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00
8555,02/29/2024 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,03/16/1999,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,02/29/2024 15:10:06,2024-08-03 14:00:00
8556,12/23/2023 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,02/27/2024 06:48:47,2024-08-03 14:00:00
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,11/30/2000,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,02/16/2024 16:33:00,2024-08-03 14:00:00

In [58]:
# Drop rows with null values
cp_cleaned = cp.dropna()
# Save the cleaned data to a new Excel file
output_path = r"C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_habiba.xlsx"

cp_cleaned.to_excel(output_path, index=False)

print(f"Cleaned file saved successfully at: {output_path}")

Cleaned file saved successfully at: C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_habiba.xlsx

In [ ]:
import pandas as pd

# Read Excel file but keep all columns as strings first
cp1 = pd.read_excel(r"C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_habiba.xlsx", dtype=str)

""
# Convert only the true date columns to datetime
date_columns = [
    "Learner SignUp DateTime",
    "Opportunity End Date",
    "Date of Birth",
    "Entry created at",
    "Apply Date",
    "Opportunity Start Date"
]

for col in date_columns:
    cp1[col] = pd.to_datetime(cp1[col], format='mixed', errors='coerce')

cp1["Date of Birth"] = pd.to_datetime(cp1["Date of Birth"], format='mixed', errors='coerce').dt.date


print(cp1.dtypes)

#inputting nan is some missing valus (handling missing data)
cp1['Opportunity Start Date']=cp1['Opportunity Start Date'].fillna('unknown')

# Drop null rows and save cleaned file
cp_cleaned = cp1.dropna()
output_path = r"C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_1.xlsx"

cp_cleaned.to_excel(output_path, index=False)

print(f"✅ Cleaned file saved successfully at: {output_path}")
print(cp_cleaned.shape)

Learner SignUp DateTime    datetime64[ns]
Opportunity Id                     object
Opportunity Name                   object
Opportunity Category               object
Opportunity End Date       datetime64[ns]
First Name                         object
Date of Birth                      object
Gender                             object
Country                            object
Institution Name                   object
Current/Intended Major             object
Entry created at           datetime64[ns]
Status Description                 object
Status Code                        object
Apply Date                 datetime64[ns]
Opportunity Start Date     datetime64[ns]
dtype: object
✅ Cleaned file saved successfully at: C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_1.xlsx
(6839, 16)

In [ ]:
import pandas as pd

# Read Excel file but keep all columns as strings first
cp2 = pd.read_excel(r"C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_1.xlsx", dtype=str)

#Handling Inconsistent country names based on unique vallues details:
cp2['Country'] = cp2['Country'].str.replace('U.S.', 'United States')
cp2['Country'] = cp2['Country'].str.replace('Iran, Islamic Republic of Persian Gulf', 'Iran')
cp2['Country'] = cp2['Country'].str.replace('Iran  Islamic Republic of Persian Gulf', 'Iran')

# Drop null rows and save cleaned file
cp_cleaned = cp2.dropna()

output_path = r"C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_T1.xlsx"

cp_cleaned.to_excel(output_path, index=False)

print(f"✅ Cleaned file saved successfully at: {output_path}")
print(cp2.shape)
cp.head()

✅ Cleaned file saved successfully at: C:\Users\maruf\my Git\internship_week1\week1\SLU_Opportunity_Wise_Data_Cleaned_T1.xlsx
(6839, 16)

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,2023-06-14 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Faria,2001-12-01 00:00:00,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,2023-06-14 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Poojitha,2000-08-16 00:00:00,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-08-29 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Amrutha Varshini,1999-01-11 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39
3,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Vinay Varshith,2000-04-19 00:00:00,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39
4,2023-05-31 07:11:04,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Fardeen,2001-09-09 00:00:00,Male,India,Illinois Institute of Technology,Computer Science and Engineering,2024-11-03 12:01:41,Withdraw,1110,2023-06-14 05:29:41,2022-03-11 18:30:39